# Generated by Django 5.0.3 on 2024-04-03 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField(verbose_name='rental date')),
                ('price', models.IntegerField()),
                ('car_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.car')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.customer')),
            ],
        ),
    ]
